import React, { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Search, Trash2, ChevronLeft, Plus } from 'lucide-react';
import { patientService } from '../../services/patientService';
import { pathologyService } from '../../services/pathologyService';
import { pathologyLabOrderService } from '../../services/pathologyLabOrderService';
import type { PatientDto } from '../../types/patient';
import type { PathologyTestDto } from '../../types/pathology';
import { useApiError } from '../../hooks/useApiError';
import { useToast } from '../../hooks/useToast';
import { PageHeader } from '../../components/common/PageHeader';
import { Card } from '../../components/common/Card';
import { Button } from '../../components/common/Button';
import { ErrorAlert } from '../../components/common/ErrorAlert';
import { ToastContainer } from '../../components/common/Toast';
import { formatCurrency } from '../../utils/formatters';

export const PathologyLabOrderFormPage: React.FC = () => {
  const navigate = useNavigate();
  const { error, clearError, handleError } = useApiError();
  const { toasts, dismiss, success } = useToast();
  const [query, setQuery] = useState(''); const [patientResults, setPatientResults] = useState<PatientDto[]>([]); const [selectedPatient, setSelectedPatient] = useState<PatientDto | null>(null); const [isSearching, setIsSearching] = useState(false);
  const [tests, setTests] = useState<PathologyTestDto[]>([]); const [selectedTests, setSelectedTests] = useState<PathologyTestDto[]>([]); const [testQuery, setTestQuery] = useState(''); const [notes, setNotes] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false); const [formError, setFormError] = useState<string | null>(null);
  useEffect(() => { void pathologyService.tests.getAll().then((data) => setTests(data.filter((test) => test.isActive))).catch(handleError); }, [handleError]);
  const searchPatients = useCallback(async () => { if (!query.trim()) { setPatientResults([]); return; } setIsSearching(true); try { setPatientResults(await patientService.search(query.trim())); } catch (err) { handleError(err); } finally { setIsSearching(false); } }, [query, handleError]);
  const addTest = (test: PathologyTestDto) => { if (!selectedTests.some((item) => item.id === test.id)) setSelectedTests((current) => [...current, test]); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); clearError(); setFormError(null); if (!selectedPatient) { setFormError('Select a patient before creating the order.'); return; } if (!selectedTests.length) { setFormError('Add at least one pathology test.'); return; } setIsSubmitting(true); try { const order = await pathologyLabOrderService.create({ patientId: selectedPatient.id, clinicalNotes: notes.trim() || undefined, items: selectedTests.map((test) => ({ pathologyTestId: test.id })) }); success('Lab order created successfully.'); navigate(`/pathology/lab-orders/${order.id}`, { state: { toast: 'Lab order created successfully.' } }); } catch (err) { handleError(err); } finally { setIsSubmitting(false); } };
  const visibleTests = tests.filter((test) => `${test.code} ${test.name}`.toLowerCase().includes(testQuery.toLowerCase()));
  return <form className="space-y-6" onSubmit={submit}>
    <PageHeader title="Create Lab Order" subtitle="Select an active patient and one or more active pathology tests." breadcrumbs={[{ label: 'Pathology', path: '/pathology' }, { label: 'Lab Orders', path: '/pathology/lab-orders' }, { label: 'New Order' }]} actions={<Button type="button" variant="outline" leftIcon={<ChevronLeft className="w-4 h-4" />} onClick={() => navigate('/pathology/lab-orders')}>Back to Orders</Button>} />
    {(error || formError) && <ErrorAlert error={formError || error} onDismiss={() => { setFormError(null); clearError(); }} />}
    <Card title="Patient" subtitle="Search the active patient directory; patient IDs are never entered manually."><div className="space-y-3">
      {!selectedPatient ? <><div className="flex gap-2"><label className="relative flex-1"><span className="sr-only">Search patient</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), void searchPatients())} placeholder="Search patient number, name, or phone..." className="w-full pl-9 pr-3 py-2 border border-slate-200 rounded-lg bg-slate-50 text-sm" /></label><Button type="button" variant="outline" onClick={() => void searchPatients()} isLoading={isSearching}>Search</Button></div>{patientResults.length > 0 && <ul className="divide-y border border-slate-200 rounded-lg max-h-56 overflow-y-auto">{patientResults.map((patient) => <li key={patient.id}><button type="button" onClick={() => { setSelectedPatient(patient); setPatientResults([]); }} className="w-full p-3 text-left hover:bg-blue-50"><span className="font-medium text-slate-900">{patient.fullName}</span><span className="ml-2 font-mono text-xs text-slate-500">{patient.patientNumber}</span><span className="block text-xs text-slate-500">{patient.age ?? '—'} yrs · {patient.gender} · {patient.phone || 'No phone'}</span></button></li>)}</ul>}</> : <div className="p-4 rounded-lg bg-blue-50 border border-blue-100 flex flex-wrap justify-between gap-3"><div><p className="font-semibold text-slate-900">{selectedPatient.fullName} <span className="font-mono text-xs text-blue-700">{selectedPatient.patientNumber}</span></p><p className="text-sm text-slate-600">{selectedPatient.age ?? '—'} yrs · {selectedPatient.gender} · {selectedPatient.phone || 'No phone'}</p></div><Button type="button" variant="ghost" size="sm" onClick={() => setSelectedPatient(null)}>Change patient</Button></div>}
    </div></Card>
    <Card title="Tests" subtitle="Only active tests returned by the pathology test master can be selected."><div className="space-y-4"><label className="block"><span className="sr-only">Find pathology test</span><input value={testQuery} onChange={(e) => setTestQuery(e.target.value)} placeholder="Find test by code or name..." className="w-full px-3 py-2 border border-slate-200 rounded-lg bg-slate-50 text-sm" /></label><div className="max-h-52 overflow-y-auto border border-slate-200 rounded-lg divide-y">{visibleTests.map((test) => <div key={test.id} className="p-3 flex items-center justify-between gap-3"><div><p className="font-medium text-slate-900"><span className="font-mono text-xs text-blue-700">{test.code}</span> {test.name}</p><p className="text-xs text-slate-500">Sample: {test.sampleTypeName || '—'} · Unit: {test.unitSymbol || '—'} · {formatCurrency(test.price)}</p></div><Button type="button" size="sm" variant="outline" disabled={selectedTests.some((item) => item.id === test.id)} leftIcon={<Plus className="w-3.5 h-3.5" />} onClick={() => addTest(test)}>Add</Button></div>)}{!visibleTests.length && <p className="p-4 text-sm text-slate-500">No active pathology tests match this search.</p>}</div>
      <div className="overflow-x-auto"><table className="w-full text-sm"><caption className="text-left font-semibold text-slate-900 mb-2">Selected Tests</caption><thead className="text-xs text-slate-500 border-b"><tr><th className="py-2 text-left">Test</th><th className="py-2 text-left">Sample</th><th className="py-2 text-left">Unit</th><th className="py-2 text-right">Price</th><th /></tr></thead><tbody>{selectedTests.map((test) => <tr key={test.id} className="border-b"><td className="py-2"><span className="font-mono text-xs">{test.code}</span> {test.name}</td><td>{test.sampleTypeName || '—'}</td><td>{test.unitSymbol || '—'}</td><td className="text-right">{formatCurrency(test.price)}</td><td className="text-right"><Button type="button" size="sm" variant="ghost" aria-label={`Remove ${test.name}`} onClick={() => setSelectedTests((items) => items.filter((item) => item.id !== test.id))}><Trash2 className="w-4 h-4 text-rose-600" /></Button></td></tr>)}</tbody></table></div>
    </div></Card>
    <Card title="Clinical Notes" subtitle="Optional; M9 accepts up to 2,000 characters."><label><span className="sr-only">Clinical notes</span><textarea value={notes} maxLength={2000} onChange={(e) => setNotes(e.target.value)} rows={4} className="w-full p-3 border border-slate-200 rounded-lg bg-slate-50 text-sm" placeholder="Relevant clinical notes for the laboratory..." /><span className="text-xs text-slate-500">{notes.length}/2000</span></label></Card>
    <div className="sticky bottom-0 bg-white/95 border border-slate-200 rounded-xl p-4 flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => navigate('/pathology/lab-orders')}>Cancel</Button><Button type="submit" isLoading={isSubmitting}>Create Lab Order</Button></div><ToastContainer toasts={toasts} onDismiss={dismiss} />
  </form>;
};
