import apiClient from '../api/client';
import { API_ENDPOINTS } from '../api/endpoints';
import type { ApiResponse } from '../types/api';
import type { PatientDto, CreatePatientRequest, UpdatePatientRequest } from '../types/patient';

/**
 * Service for Patient Master (M8) CRUD and search operations.
 * Uses the centralized apiClient — do not create separate Axios instances.
 */
export const patientService = {
  /**
   * Returns all active patients for the current hospital.
   * GET /api/patients
   */
  async getAll(): Promise<PatientDto[]> {
    const response = await apiClient.get<ApiResponse<PatientDto[]>>(API_ENDPOINTS.PATIENTS.BASE);
    return response.data.data ?? [];
  },

  /**
   * Returns a specific patient by database ID.
   * GET /api/patients/{id}
   */
  async getById(id: number): Promise<PatientDto> {
    const response = await apiClient.get<ApiResponse<PatientDto>>(API_ENDPOINTS.PATIENTS.BY_ID(id));
    if (response.data.data) {
      return response.data.data;
    }
    throw new Error(response.data.message || 'Patient not found');
  },

  /**
   * Searches active patients by PatientNumber, FirstName, LastName, or Phone.
   * GET /api/patients/search?query={value}
   */
  async search(query: string): Promise<PatientDto[]> {
    const response = await apiClient.get<ApiResponse<PatientDto[]>>(API_ENDPOINTS.PATIENTS.SEARCH, {
      params: { query },
    });
    return response.data.data ?? [];
  },

  /**
   * Registers a new patient. PatientNumber is generated by the backend.
   * POST /api/patients
   */
  async create(dto: CreatePatientRequest): Promise<PatientDto> {
    const response = await apiClient.post<ApiResponse<PatientDto>>(API_ENDPOINTS.PATIENTS.BASE, dto);
    if (response.data.data) {
      return response.data.data;
    }
    throw new Error(response.data.message || 'Failed to register patient');
  },

  /**
   * Updates an existing patient's profile.
   * isActive is always forwarded from the caller — the form must never change it.
   * PUT /api/patients/{id}
   */
  async update(id: number, dto: UpdatePatientRequest): Promise<PatientDto> {
    const response = await apiClient.put<ApiResponse<PatientDto>>(API_ENDPOINTS.PATIENTS.BY_ID(id), dto);
    if (response.data.data) {
      return response.data.data;
    }
    throw new Error(response.data.message || 'Failed to update patient');
  },

  /**
   * Soft-deletes (deactivates) a patient. The database record is preserved.
   * DELETE /api/patients/{id}
   */
  async deactivate(id: number): Promise<void> {
    await apiClient.delete<ApiResponse<PatientDto>>(API_ENDPOINTS.PATIENTS.BY_ID(id));
  },

  /**
   * Re-activates a previously deactivated patient via PUT with isActive=true.
   * This is a separate explicit action — never triggered from the normal edit form.
   * PUT /api/patients/{id}  (with isActive: true forwarded)
   */
  async reactivate(patient: PatientDto): Promise<PatientDto> {
    const dto: UpdatePatientRequest = {
      firstName: patient.firstName,
      middleName: patient.middleName,
      lastName: patient.lastName,
      dateOfBirth: patient.dateOfBirth,
      gender: patient.gender,
      bloodGroup: patient.bloodGroup,
      phone: patient.phone,
      email: patient.email,
      address: patient.address,
      city: patient.city,
      state: patient.state,
      postalCode: patient.postalCode,
      emergencyContactName: patient.emergencyContactName,
      emergencyContactPhone: patient.emergencyContactPhone,
      isActive: true,
    };
    return this.update(patient.id, dto);
  },
};
