import apiClient from '../api/client';
import { API_ENDPOINTS } from '../api/endpoints';
import type { ApiResponse } from '../types/api';
import type {
  StaffDto,
  CreateStaffRequest,
  UpdateStaffRequest,
  StaffQueryFilters,
} from '../types/staff';

/**
 * Service for Hospital Staff Master (F14.3) operations.
 * Connects directly to backend StaffController.
 */
export const staffService = {
  /**
   * Retrieves all active staff members for the current hospital tenant,
   * optionally filtered by departmentId or search query.
   * GET /api/staff?departmentId={id}&search={query}
   */
  async getAll(filters?: StaffQueryFilters): Promise<StaffDto[]> {
    const params: Record<string, string | number> = {};
    if (filters?.departmentId) {
      params.departmentId = filters.departmentId;
    }
    if (filters?.search && filters.search.trim()) {
      params.search = filters.search.trim();
    }

    const res = await apiClient.get<ApiResponse<StaffDto[]>>(
      API_ENDPOINTS.STAFF.BASE,
      { params }
    );
    return res.data.data || [];
  },

  /**
   * Retrieves a specific staff member by database ID.
   * GET /api/staff/{id}
   */
  async getById(id: number): Promise<StaffDto> {
    const res = await apiClient.get<ApiResponse<StaffDto>>(
      API_ENDPOINTS.STAFF.BY_ID(id)
    );
    if (res.data.data) return res.data.data;
    throw new Error(res.data.message || 'Staff member not found');
  },

  /**
   * Retrieves a single staff member by unique EmployeeNumber.
   * GET /api/staff/number/{employeeNumber}
   */
  async getByEmployeeNumber(employeeNumber: string): Promise<StaffDto> {
    const res = await apiClient.get<ApiResponse<StaffDto>>(
      API_ENDPOINTS.STAFF.BY_NUMBER(employeeNumber)
    );
    if (res.data.data) return res.data.data;
    throw new Error(res.data.message || 'Staff member not found');
  },

  /**
   * Registers a new staff member.
   * EmployeeNumber is auto-generated by the backend.
   * POST /api/staff
   */
  async create(dto: CreateStaffRequest): Promise<StaffDto> {
    const res = await apiClient.post<ApiResponse<StaffDto>>(
      API_ENDPOINTS.STAFF.BASE,
      dto
    );
    if (res.data.data) return res.data.data;
    throw new Error(res.data.message || 'Failed to create staff member');
  },

  /**
   * Updates an existing staff member's profile.
   * PUT /api/staff/{id}
   */
  async update(id: number, dto: UpdateStaffRequest): Promise<StaffDto> {
    const res = await apiClient.put<ApiResponse<StaffDto>>(
      API_ENDPOINTS.STAFF.BY_ID(id),
      dto
    );
    if (res.data.data) return res.data.data;
    throw new Error(res.data.message || 'Failed to update staff member');
  },

  /**
   * Soft-deactivates a staff member (sets IsActive = false).
   * DELETE /api/staff/{id}
   */
  async deactivate(id: number): Promise<StaffDto> {
    const res = await apiClient.delete<ApiResponse<StaffDto>>(
      API_ENDPOINTS.STAFF.BY_ID(id)
    );
    if (res.data.data) return res.data.data;
    return { id } as StaffDto;
  },

  /**
   * Reactivates a previously deactivated staff member.
   * PUT /api/staff/{id} with isActive = true
   */
  async reactivate(staff: StaffDto): Promise<StaffDto> {
    const updateDto: UpdateStaffRequest = {
      firstName: staff.firstName,
      middleName: staff.middleName || undefined,
      lastName: staff.lastName || undefined,
      departmentId: staff.departmentId,
      designation: staff.designation || undefined,
      phone: staff.phone || undefined,
      email: staff.email || undefined,
      joiningDate: staff.joiningDate || undefined,
      isActive: true,
    };
    return this.update(staff.id, updateDto);
  },
};

export default staffService;
